Done level 6
evgenysavonkin/autopark_jcore pull request #1
Opened 2024-02-25 16:13 UTC by evgenysavonkin

2024-02-26 08:19 UTC, nikoteressi requested changes
В целом всё хорошо. Но было бы лучше избегать дублирования кода, старайся смотреть на код как на абстракцию. Сосредотачивайся не на прямо на конкретной задаче, а на абстрактных функциях которые она должна выполнять. Так ты сможешь понять\увидеть места где есть схожая логика, и написать код так, что бы его можно было переиспользовать, а не писать почти такой же

2024-02-26 08:19 UTC, nikoteressi commented on src/main/java/org/evgenysav/util/FileActions.java
> +    }
Если внимательно присмотреться, то эти три метода выполняют по сути одну и ту же логику: делают чтение из файла, и создают список с объектами. Подумай, как бы можно было вынести логику так, что бы сделать это всё в одном методе, с использованием case/ if-else и т.п.

2024-02-26 08:19 UTC, nikoteressi commented on src/main/java/org/evgenysav/util/FileActions.java
> +    }
Та же история, что и выше

2024-02-26 09:02 UTC, evgenysavonkin commented on src/main/java/org/evgenysav/util/FileActions.java
> +    }
Подправил в следующем коммите, повторяющийся код инкапсулировал в generic-методы, однако есть нюанс в безопасности кастов, всё работает, но идея ругается на Unchecked cast.

2024-02-27 15:31 UTC, nikoteressi approved these changes

2024-02-27 15:32 UTC, merged